VIA_ENABLE = yes
VIAL_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
QMK_SETTINGS = yes
LTO_ENABLE = yes

KEY_OVERRIDE_ENABLE = no
REPEAT_KEY_ENABLE = no
CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no

RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
VIALRGB_ENABLE = no
AUDIO_ENABLE = no
